# Индивидуальное задание номер 1.

## Уплотнить заданную матрицу, удаляя из нее строки и столбцы, в которых есть хотя бы $1$ нуль. Найти номер первой из строк, содержащих хотя бы один положительный элемент. 

### Импортируем нужную нам библиотеку

In [73]:
import numpy as np

In [74]:
# Создание случайной матрицы
rows = 5
cols = 5
matrix = np.random.randint(-5, 5, size=(rows, cols))
print(matrix)

[[-1 -4  1 -5 -4]
 [-5 -3  4 -5  4]
 [ 0  2  0  0 -1]
 [-5  2 -1 -1 -3]
 [-2  3 -2  4 -2]]


### Создаем функцию, которая будет уплотнять нашу матрицу.

In [75]:
def remove_zero_rows_cols(matrix):
    row_indices = np.where(~np.any(matrix == 0, axis=1))[0]
    col_indices = np.where(~np.any(matrix == 0, axis=0))[0]
    result_matrix = matrix[row_indices][:, col_indices]

    return result_matrix

### Создаём функцию, которая будет находить первую строку с хотя бы одним положительным элементом.

In [76]:
def find_first_positive_row(matrix):
    row_indices = np.where(np.any(matrix > 0, axis=1))[0]
    if len(row_indices) > 0:
        return row_indices[0]
    else:
        return -1

### Используем наши функции и выводим уплотнённую матрицу.

In [77]:

# Уплотнение матрицы
result_matrix = remove_zero_rows_cols(matrix)
print("Уплотненная матрица:")
print(result_matrix)

# Поиск номера первой строки с положительными элементами
first_positive_row = find_first_positive_row(result_matrix)
print("Номер первой строки с положительными элементами:", first_positive_row)

Уплотненная матрица:
[[-4 -4]
 [-3  4]
 [ 2 -3]
 [ 3 -2]]
Номер первой строки с положительными элементами: 1
